name: nathan-project
channels:
  - pytorch
  - anaconda
  - conda-forge
  - huggingface
dependencies:
  - python=3.6
  - pytorch=1.8.1
  - transformers=4.6.1
  - numpy
  - pandas
  - scikit-learn
  - scipy
  - tqdm
  - ipykernel
  - matplotlib
  - jupyter
  - tensorboardX
  - tensorboard
  - seqeval
  - pyahocorasick
  - statsmodels
  - biopython
  - sentencepiece=0.1.91